@startuml
start

if (问号个数奇偶性) then (奇数)
  :Alice 获胜;
note right: 最后一个数字是 Alice 填写
else (偶数)
  if (左右除问号外的和是否相等) then (相等)
    if (左右问号个数是否相等) then (相等)
      :Bob 获胜;
note
Bob 只需要在另外一边重复
Alice 的操作即可
end note
    else (不等)
      :Alice 获胜;
note
Alice 只需要在问号较多的一边填 9 ，
另一边填 0 即可
end note
    endif
  else (不等)
    if (左右问号个数是否相等) then (相等)
      :Alice 获胜;
note
Alice 只需要在和较大的一边填 9 ，
另一边填 0 即可
end note
    else (不等)
        if (问号多的一边和是否大于另一边) then (大于)
            :Alice 获胜;
            note
Alice 只需要在问号较多的一边填 9 ，
另一边填 0 即可
end note
        else (小于)
            if (abs(leftQuestion - rightQuestion) / 2 * 9 与 abs(leftSum - rightSum) 的大小关系) then (相等)
            :Bob 获胜;
note
若这一边的和小于另一边，则 Alice 会重复填 0 ，Bob 填 9
即使 Alice 任填一个数 num ，Bob 也可以填 9 - num 补齐为 9 。
如此操作，直到所有问号填写完毕。
end note
            else (不等)
            :Alice 获胜;
            endif
        endif
    endif
  endif
endif

stop
@enduml